image: debian:latest

before_script:
  - apt-get update -qq && apt-get install -y g++ build-essential  doxygen graphviz git
  - g++ --version
  - which g++

build:
  script:
  - uname -m
  - mkdir -p /home/user
  - cd /home/user/
  - /bin/echo -e -n '#include <iostream>\nint main(void){std::cout<<"Hello C++"<<std::endl;return 0;}\n' > main.cpp
  - g++ main.cpp -o hello.C++ && ./hello.C++
  - ./hello.C++ > hello.txt
  - ls *

