image: debian:latest

before_script:
  ##g++
  - apt-get update -qq && apt-get install -y g++ build-essential  doxygen graphviz  git
  - g++ --version
  - which g++
  ##git
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name  "$GITLAB_USER_NAME"
  ##docker container
#  - printenv

build:
  script:
  ##docker container
  - uname -m
#  - printenv
  ##imported repository
  - cd /builds/$CI_PROJECT_PATH
  - ls
  - grep url /builds/$CI_PROJECT_PATH/.git/config
  - git branch -a
  - git checkout -b CI_$CI_BUILD_REF_NAME
  ##repository
  - mkdir -p /home/user
  - cd /home/user/
  - git clone /builds/$CI_PROJECT_PATH .
  - git branch -a
  - ls *

  ##make all e.g. bin, doc, run, ...
  - make
  - ls *

  ##commit
  - git add $CI_BUILD_REF_NAME'_help.output'
  - git add doc/html/index.html
  - git commit -am 'CI output'
  ##push
  - cd /builds/$CI_PROJECT_PATH
  - git checkout $CI_BUILD_REF_NAME
  - cd /home/user/
  - git push

