image: debian:latest

before_script:
  ##g++
  - apt-get update -qq && apt-get install -y g++ build-essential  doxygen graphviz  git
  - g++ --version
  - which g++

build:
  script:
  - uname -m
  - cd /builds/SebastienCOUDERT/stdcpp
  - ls
  - grep url /builds/SebastienCOUDERT/stdcpp/.git/config
  - git branch -a
  ##repository
  - mkdir -p /home/user
  - cd /home/user/
  - git clone /builds/SebastienCOUDERT/stdcpp .
  - git branch -a
  - ls *
  ##build
  - make
  - ./hello.C++ > hello.txt
  - ls *

