# Use the official gcc image
image: gcc

before_script:
    # Install build dependencies
    - apt-get update && apt-get -y install make doxygen

# Stage "build"
run-build:
    # Build the application
    stage: build
    script:
        - mkdir build
        - cd build
        - make
        - echo "hop gitlab-ci.yml" > build/hop.txt

  # This stage is only executed for new tags
  only:
    - tags

  # The files which are to be made available in GitLab
  artifacts:
    paths:
      - build/*
