image: debian:latest

before_script:
  ##g++
  - apt-get update -qq && apt-get install -y g++ build-essential  doxygen graphviz git
  - g++ --version
  - which g++

build:
  script:
  - uname -m
  - ls /builds/SebastienCOUDERT/stdcpp
  - grep url /builds/SebastienCOUDERT/stdcpp/.git/config
  - mkdir -p /home/user
  - cd /home/user/
  - git clone /builds/SebastienCOUDERT/stdcpp .
  - git checkout hello
  - ls *
  - make
  - ./hello.C++ > hello.txt
  - ls *


