image: debian:latest

before_script:
  ##g++
  - apt-get update -qq && apt-get install -y g++ build-essential  doxygen graphviz  git
  - g++ --version
  - which g++
  ##git
  - git config --global user.email "sebastien.coudert@ganil.fr"
  - git config --global user.name  "Sebastien COUDERT"

build:
  script:
  ##docker container
  - uname -m
  ##imported repository
  - cd /builds/SebastienCOUDERT/stdcpp
  - ls
  - grep url /builds/SebastienCOUDERT/stdcpp/.git/config
  - git branch -a
  - git checkout -b CI_hello
  ##repository
  - mkdir -p /home/user
  - cd /home/user/
  - git clone /builds/SebastienCOUDERT/stdcpp .
  - git branch -a
  - ls *

  ##build binary
  - make
  ##run binary
  - ./hello.C++ > hello.txt
  - ls *
  ##documentation
  - doxygen && ls -lah doc/html

  ##commit
  - git add hello.txt
  - git commit -am 'CI output'
  ##push
  - cd /builds/SebastienCOUDERT/stdcpp
  - git checkout hello
  - cd /home/user/
  - git push

