image: debian:latest

stages:
    - build
    - deploy

before_script:
  ##g++
  - apt-get update -qq && apt-get install -y g++ build-essential  doxygen graphviz  git
  - g++ --version
  - which g++
  ##git
  - git config --global user.email "$GITLAB_USER_EMAIL"
  - git config --global user.name  "$GITLAB_USER_NAME"
  ##boost
  - apt-get install -y libboost-dev
  ##docker container
#  - printenv

build:
  stage: build
  script:
  ##docker container
  - uname -m
#  - printenv
  ##imported repository
  - cd $CI_PROJECT_DIR
  - ls
  - grep url $CI_PROJECT_DIR/.git/config
  - git branch -a
  - git checkout -b CI_$CI_BUILD_REF_NAME
  ##repository
  - mkdir -p /home/user
  - cd /home/user/
  - git clone $CI_PROJECT_DIR .
  - git branch -a
  - ls *

  ##make all e.g. bin, doc, run, ...
  - make
  - ls *

  ##commit
  - git add VERSION $CI_BUILD_REF_NAME'_help.output'
  - git add doc/html
  - uname -m > ARCH.txt
  - git add ARCH.txt
  - git commit -am 'CI output'
  ##push
  - cd /builds/$CI_PROJECT_PATH
  - git checkout $CI_BUILD_REF_NAME
  - git branch
  - cd /home/user/
  - git push
  #artifacts dir.
  - cd $CI_PROJECT_DIR
  - git checkout CI_$CI_BUILD_REF_NAME
  - ls $CI_PROJECT_DIR
#  - echo $CI_PROJECT_DIR
#  - git push --set-upstream origin CI_hello

  artifacts:
    expose_as: 'built in container'
    paths:
    - ARCH.txt
    - VERSION
    - hello_help.output
    - doc/html

pages:
  stage: deploy
  script:
  - pwd
  - mkdir public/
#  - /bin/echo -e -n "<html>\n<head>\n<title>GitLab//Pages</title>\n</head>\n<body>\n<h1>HTML pages</h1>\n</body>\n</html>\n" > public/index.html
  ##doxygen output
  - mv doc/html/* public/
  ##built with CI
  - mkdir public/built/
  - /bin/echo -e -n "<html>\n<head>\n<title>GitLab//Pages/CI/built</title>\n</head>\n<body>\n" > public/built/index.html
  - /bin/echo -e -n "<h1>CI architecture</h1>\n<pre>\n" >> public/built/index.html
  - cat ARCH.txt >> public/built/index.html
  - /bin/echo -e -n "</pre>\n\n<h1>program</h1>\n" >> public/built/index.html
  - /bin/echo -e -n "<h2>version</h2>\n<pre>\n" >> public/built/index.html
  - cat VERSION >> public/built/index.html
  - /bin/echo -e -n "</pre>\n\n<h2>help</h2>\n<pre>\n" >> public/built/index.html
  - cat hello_help.output >> public/built/index.html
  - /bin/echo -e -n "</pre>\n\n</body>\n</html>\n" >> public/built/index.html
  - mv ARCH.txt VERSION hello_help.output public/built/
  ##output links
  - echo "firefox https://sebastiencoudert.pages.in2p3.fr/stdcpp/"
  - echo "firefox https://sebastiencoudert.pages.in2p3.fr/stdcpp/built/"
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

